Iss hipcms 474 forgot password
HiP-App/HiP-Auth pull request #10
Opened 2016-11-10 12:44 UTC by nagaraj1993

2016-11-10 14:05 UTC, maltehol requested changes
Synchronize use of async methods.
German Translations

2016-11-10 14:05 UTC, maltehol commented on src/Auth/Controllers/AuthController.cs
> +                        var result = await _userManager.ResetPasswordAsync(user, model.Email, password);
We don't use async function if we wait directly for it.
Use `ResetPasswort()` instead

2016-11-10 14:05 UTC, maltehol commented on src/Auth/Controllers/AuthController.cs
> +                            }
It's ok to send mails Async. But we don't have to wait for a result.

2016-11-10 14:05 UTC, maltehol commented on src/Auth/Utility/EmailSender.cs
> +            message.From.Add(new MailboxAddress("History in Paderborn", "noreply@hipapp.de"));
Use the entry of the Config instead of hardcode the email `noreply@hipapp.de`.

2016-11-10 14:05 UTC, maltehol commented on src/Auth/Utility/EmailSender.cs
> +            message.Subject = "History in Paderborn App Neue Passwort";
Use "Neues Password für die History in Paderborn App" as Subject. (It's better German)

2016-11-10 14:05 UTC, maltehol commented on src/Auth/Utility/PasswordGenerator.cs
> +        for (int count = 0; count <= passwordLength - 1; count++)
use `count < passwordLenght` It's easier to read and does the same

2016-11-10 14:05 UTC, maltehol commented on src/Auth/Utility/invitation-forgot-password.html
> +    <p>Please use this <a href="http://docker-hip.cs.upb.de/login/?email={email}">Link to login with your new password</a></p>
We should send an German mail. 

"Dein neues Password ist: "'Password'"
Unter <a....>HiP-Cms<a/> kannst du dich jetzt mit deinem neuem Password anmelden"

2016-11-17 10:50 UTC, sstamm commented
AspNetCore Identity already offers a solution for this problem:
https://docs.microsoft.com/en-us/aspnet/core/security/authentication/accconfirm
Goal should be to benefit from this.

2016-11-17 10:50 UTC, closed without merging